### ISSUE TITLE
Load order is non-deterministic

### ISSUE THREAD

**Issue by iancanderson** [codeclimate/codeclimate-services#65]
The loading that happens in `lib/cc/service.rb` uses an unsorted call to `Dir[]`, whose order is non-deterministic, and depends on underlying OS. Sorted this result before requiring each file would make the loading more deterministic, and result in fewer disparities between local environment and production.

See http://ruby-doc.org/core-2.1.2/Dir.html#method-c-glob

**Comment by dblandin** [comment]
Hey @iancanderson!

Looks like you implemented this fix in #66, so I'm going to go ahead and close this issue.

Thanks!

**Comment by iancanderson** [comment]
Yep, looks like I forgot to close this issue. Thanks!
