### ISSUE TITLE
CodeClimate asks for more permissions than it probably needs

### ISSUE THREAD

**Issue by evilaliv3** [codeclimate/codeclimate-services#73]
While working on [GlobaLeaks](github.com/globaleaks/GlobaLeaks) i've found that CodeClimate would be a valuable tool to be integrated within the set of our on-commit CI and code quality metrics, but what from i'm viewing right know CodeClimate is asking really for too much permissions and this prevents our adoption (https://github.com/globaleaks/GlobaLeaks/issues/1265).

![screenshot from 2015-05-09 21 56 41](https://cloud.githubusercontent.com/assets/217034/7551876/189caec6-f699-11e4-90c4-8b0f32f1ac60.png)

[Landscape.io](https://landscape.io) that makes the same work using a python linter require really less and more precise permissions:
![screenshot from 2015-05-09 21 53 50](https://cloud.githubusercontent.com/assets/217034/7551795/142cbe88-f696-11e4-91a8-0885af66ac61.png)

**Comment by pbrisbin** [comment]
Hi @evilaliv3, sorry for the delayed response here. We recently re-worked how and when we ask for the OAuth scopes we need. In doing so, I believe this issue is addressed. Feel free to re-open if that's not the case.

**Comment by nallar** [comment]
This seems to have been closed incorrectly.

Code climate still needs for write access to repositories.

github's roadmap lists granular access permissions, so it seems that it will be possible to properly fix this soon: https://developer.github.com/early-access/platform-roadmap/

**Comment by evilaliv3** [comment]
I agree with @nallar; i still consider this as an important improvement to be applied.
